Repository allendomingo/StoreInventory, pull requests merged in 2022-08, with the labels that each got.

#93 [NET-0092] Initialize AntDesign
  inventory-web-app/package-lock.json
  inventory-web-app/package.json
  inventory-web-app/pages/index.js
  inventory-web-app/styles/globals.css
  inventory-web-app/yarn.lock
Labels: enhancement, fe

#101 [NET-0098] Fix Lint Issues
  .github/workflows/Lint.yml
Labels: bug

#105 [NET-0098] Fix Lint Github Action for NextJS FE App
  .github/workflows/Lint.yml
Labels: bug

#110 [NET-0092] Install Ant Design Icon and TailwindCSS packages
  inventory-web-app/package-lock.json
  inventory-web-app/package.json
  inventory-web-app/pages/index.js
  inventory-web-app/postcss.config.js
  inventory-web-app/styles/globals.css
  inventory-web-app/tailwind.config.js
  inventory-web-app/yarn.lock
Labels: fe
